name: RedZone
favicon: null
layout_spectrum: 0.7740241617430001
typography_spectrum: 0.770425524096936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f01111'
    - '#fcfcf8'
    - '#f67977'
    - '#f9c0bd'
    - '#000000'
  brandStrength: 0.8181133707985282
  lightness: 0.5545084944460541
  saturation: 0.9393122920300812
  rhythmicContrast: 0.7412411188706756
purpose: []
